version: '3.9'
services:
  db:
    container_name: mysql-kp
    command: --default-authentication-plugin=mysql_native_password --local-infile=1
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kp
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  
  app:
    container_name: kp-app
    build: .
    env_file:
      - .env
    ports:
      - "6565:6565"
    depends_on:
      - db

volumes:
  data: