// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repositories

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForCreateCustomersLimits uint32 = 1

func convertRowsForCreateCustomersLimits(w *io.PipeWriter, arg []CreateCustomersLimitsParams) {
	e := mysqltsv.NewEncoder(w, 4, nil)
	for _, row := range arg {
		e.AppendString(row.CustomerLimitID)
		e.AppendString(row.CustomerID)
		e.AppendString(row.LimitAmount)
		e.AppendValue(row.Tenor)
	}
	w.CloseWithError(e.Close())
}

// CreateCustomersLimits uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) CreateCustomersLimits(ctx context.Context, arg []CreateCustomersLimitsParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("CreateCustomersLimits_%d", atomic.AddUint32(&readerHandlerSequenceForCreateCustomersLimits, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForCreateCustomersLimits(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `kp_customers_limits` %s (customer_limit_id, customer_id, limit_amount, tenor)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
