// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customers.sql

package repositories

import (
	"context"
	"time"
)

const createCustomers = `-- name: CreateCustomers :exec
INSERT INTO kp_customers (
  customer_id, identification_number, full_name, legal_name, place_of_birth, date_of_birth, salary, photo_ktp, photo_selfie, user_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCustomersParams struct {
	CustomerID           string    `db:"customer_id" json:"customer_id"`
	IdentificationNumber string    `db:"identification_number" json:"identification_number"`
	FullName             string    `db:"full_name" json:"full_name"`
	LegalName            string    `db:"legal_name" json:"legal_name"`
	PlaceOfBirth         string    `db:"place_of_birth" json:"place_of_birth"`
	DateOfBirth          time.Time `db:"date_of_birth" json:"date_of_birth"`
	Salary               string    `db:"salary" json:"salary"`
	PhotoKtp             string    `db:"photo_ktp" json:"photo_ktp"`
	PhotoSelfie          string    `db:"photo_selfie" json:"photo_selfie"`
	UserID               string    `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateCustomers(ctx context.Context, arg CreateCustomersParams) error {
	_, err := q.exec(ctx, q.createCustomersStmt, createCustomers,
		arg.CustomerID,
		arg.IdentificationNumber,
		arg.FullName,
		arg.LegalName,
		arg.PlaceOfBirth,
		arg.DateOfBirth,
		arg.Salary,
		arg.PhotoKtp,
		arg.PhotoSelfie,
		arg.UserID,
	)
	return err
}
