// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"time"
)

type KpCustomer struct {
	CustomerID           string    `db:"customer_id" json:"customer_id"`
	IdentificationNumber string    `db:"identification_number" json:"identification_number"`
	FullName             string    `db:"full_name" json:"full_name"`
	LegalName            string    `db:"legal_name" json:"legal_name"`
	PlaceOfBirth         string    `db:"place_of_birth" json:"place_of_birth"`
	DateOfBirth          time.Time `db:"date_of_birth" json:"date_of_birth"`
	Salary               string    `db:"salary" json:"salary"`
	PhotoKtp             string    `db:"photo_ktp" json:"photo_ktp"`
	PhotoSelfie          string    `db:"photo_selfie" json:"photo_selfie"`
	UserID               string    `db:"user_id" json:"user_id"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time `db:"updated_at" json:"updated_at"`
}

type KpCustomersLimit struct {
	CustomerLimitID string    `db:"customer_limit_id" json:"customer_limit_id"`
	CustomerID      string    `db:"customer_id" json:"customer_id"`
	LimitAmount     string    `db:"limit_amount" json:"limit_amount"`
	Tenor           int32     `db:"tenor" json:"tenor"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

type KpTransaction struct {
	TransactionID     string    `db:"transaction_id" json:"transaction_id"`
	CustomerID        string    `db:"customer_id" json:"customer_id"`
	CustomerLimitID   string    `db:"customer_limit_id" json:"customer_limit_id"`
	ContractNumber    string    `db:"contract_number" json:"contract_number"`
	OtrAmount         string    `db:"otr_amount" json:"otr_amount"`
	AdminFee          string    `db:"admin_fee" json:"admin_fee"`
	InstallmentAmount string    `db:"installment_amount" json:"installment_amount"`
	InterestAmount    string    `db:"interest_amount" json:"interest_amount"`
	AssetName         string    `db:"asset_name" json:"asset_name"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time `db:"updated_at" json:"updated_at"`
}

type KpUser struct {
	UserID    string    `db:"user_id" json:"user_id"`
	Email     string    `db:"email" json:"email"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
