// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCustomers(ctx context.Context, arg CreateCustomersParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetCustomerLimitById(ctx context.Context, customerID string) ([]GetCustomerLimitByIdRow, error)
	GetCustomerTransactionByLimitIdAndCustomerId(ctx context.Context) ([]GetCustomerTransactionByLimitIdAndCustomerIdRow, error)
	GetCustomerTransactionOtr(ctx context.Context, arg GetCustomerTransactionOtrParams) (interface{}, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	CreateCustomersLimits(ctx context.Context, arg []CreateCustomersLimitsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
